version: 3.1.0

pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: pyannote_model_wespeaker-voxceleb-resnet34-LM.bin
    embedding_batch_size: 128  # 增加批次大小充分利用H100
    embedding_exclude_overlap: true
    segmentation: pyannote_model_segmentation-3.0.bin
    segmentation_batch_size: 128  # 增加批次大小充分利用H100

params:
  clustering:
    method: centroid
    min_cluster_size: 15
    threshold: 0.7045654963945799  # 恢復原始預設值
  segmentation:
    min_duration_off: 0.0